[package]
name = "home-alarm-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.7.0"
chrono = "0.4.38"
enum_stringify = "0.4.2"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
suncalc = "0.4.0"
